### ISSUE TITLE
Installing Dissolve 1.0.0 on Windows

### ISSUE THREAD

**Issue by MartaFalko** [disorderedmaterials/dissolve#1102]
**Describe the bug**
File tbb.dll is missing and it is impossible to open Dissolve. Once the file is downloaded separately and placed in Dissolve folder, everything is OK.

**Operating System:**
 - OS:  Windows

**Comment by trisyoungs** [comment]
@rprospero since you've just woven your magic on #1071, of course we have the same problem on Windows. Because the package is built via the `ci/windows/dissolve-gui.iss` definitions file which also takes paths to most everything else, the fix should be easier here.

I'm surprised that the Windows version doesn't also complain about ANTLR4...

**Comment by rprospero** [comment]
I'd bet £5 that, when I fix the TBB issue, it starts complaining about ANTLR4.

**Comment by trisyoungs** [comment]
I would normally take that bet too, but @MartaFalko does say that putting the tbb dll in the folder fixes things...
