### ISSUE TITLE
Filled Species box in NewConfiguration layer- empty simulation box- Dissolve on IDAaaS v 1.0.0 @47855e8a

### ISSUE THREAD

**Issue by MartaFalko** [disorderedmaterials/dissolve#1116]
**Describe the bug**
After selecting 'Water' as the Species to be used to create a new configuration, the simulation box appears to be empty. Please see the screen shots for more details

**To Reproduce**
Steps to reproduce the behaviour (if necessary):
1. Go to 'NewConfiguration' tab
2. Select Water as Species (initially only a blank box is seen next to 'Species')
3. Click 'Generate'
4. See error - the empty simulation box

**Expected behaviour**
The new configuration to be generated.

**Screenshots**
Please see the attached file.

**Operating System:**
 - Dissolve on IDAaaS
[Species box in the NewConfiguration layer.docx](https://github.com/disorderedmaterials/dissolve/files/8881867/Species.box.in.the.NewConfiguration.layer.docx)

**Comment by trisyoungs** [comment]
This is, in fact, the correct behaviour, but the reason is not explained at all in the example. The `Species` and `CoordinateSets` options are mutually exclusive - the default is to use a coordinate set source when adding molecules so that a variety of geometries of molecule are created, rather than lots of exact copies of the defined species coordinates. If you then go and set a target `Species` as well, Dissolve will complain and the configuration will not be generated (which is what you see here).

I think the solution to this is to explicitly discuss the two options in the water example.
