### ISSUE TITLE
Spin Boxes getting squashed

### ISSUE THREAD

**Issue by jswift-stfc** [disorderedmaterials/dissolve#1120]
**Describe the bug**
Spin Boxes being used throughout the GUI are squashed, so their current values are not visible. Seems like this mainly occurs in the `Control` group of layers.
This occured on a 13.3 inch display, 2560x1600. Could be a high DPI issue.

**Screenshots**
<img width="1680" alt="Screenshot 2022-06-11 at 21 04 59" src="https://user-images.githubusercontent.com/87013792/173203270-18f3c4de-539b-499e-89f8-3259ef0f2eab.png">
<img width="1680" alt="Screenshot 2022-06-11 at 21 04 30" src="https://user-images.githubusercontent.com/87013792/173203271-40acebcc-4d8c-43e5-9e01-733d7b247204.png">

**Operating System:**
 - OS:  OSX
 - OS version / flavour:  Monterey

**Comment by trisyoungs** [comment]
I think this is more likely an issue with the `ExponentialSpin` widgets, which are custom, since the integer spin variants (which are `QSpinBox` widgets) display just fine.

I've made a quick hack to try and fix this in #1124 - can you try the dmg file out and see if it works (https://dev.azure.com/DisorderedMaterials/Dissolve/_build/results?buildId=6834&view=artifacts&pathAsName=false&type=publishedArtifacts).

**Comment by jswift-stfc** [comment]
Can confirm that the changes you made work, and the `ExponentialSpin` widgets are sized correctly.
